# Generated by Django 3.1.6 on 2021-02-02 21:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clss',
            fields=[
                ('ID', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(111111), django.core.validators.MaxValueValidator(999999)])),
                ('name', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('green', models.PositiveIntegerField(default=0)),
                ('amber', models.PositiveIntegerField(default=0)),
                ('red', models.PositiveIntegerField(default=0)),
                ('live', models.BooleanField(default=False)),
                ('Clss', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='portal.clss')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280)),
                ('topic', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='portal.topic')),
            ],
        ),
    ]
